Chipyard compatibility
ucb-bar/hbwif pull request #17
Opened 2020-01-30 22:54 UTC by harrisonliew

Chipyard 1.1.0 uses a new Chisel & Rocketchip, so:
* some module types are no longer experimental
* `toBits` -> `asUInt`, `fromBits` -> `asTypeOf`
* Some `Vec`s are now `VecInit`s

Also add Abe's tieoff bbox.

2020-01-30 23:11 UTC, jwright6323 requested changes
Minor name nit, otherwise lgtm

2020-01-30 23:11 UTC, jwright6323 commented on src/main/resources/util.v
> +module TieoffDifferential (
I don't like the name Tieoff- it sounds like it's terminating. Can we rename this to BoolToDifferential?

```suggestion
module BoolToDifferential (
```

2020-01-30 23:11 UTC, jwright6323 commented on src/main/scala/unittest/Util.scala
> +class TieoffDifferential extends BlackBox {
See above

```suggestion
class BoolToDifferential extends BlackBox {
```

2020-01-30 23:11 UTC, jwright6323 commented on src/main/scala/unittest/Util.scala
> +object TieoffDifferential {
See above

```suggestion
object BoolToDifferential {
```

2020-01-30 23:56 UTC, abejgonzalez commented on src/main/resources/util.v
> +module TieoffDifferential (
I agree. I think it was originally `Bool`?

2020-01-31 00:19 UTC, jwright6323 approved these changes

2020-01-31 05:19 UTC, merged